Repository JuliaGPU/KernelAbstractions.jl, pull requests merged in 2020-12, with the labels that each got.

#150 Add locking to stream GC
  src/backends/cuda.jl
Labels: bug

#160 Add the Buildkite status badges, and fix the Bors config
  README.md
  bors.toml
Labels: bug, documentation

#164 README: Add the Bors badge
  README.md
Labels: documentation
